spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  application:
    name: springcloud-config-client
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-dev.com:7001/eureka/
info:
  app.name: springcloudhelloworld
  company.name: www.springcloudhelloworld.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
---
server:
  port: 8202
spring:
  application:
    name: springcloud-config-client
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-test.com:7001/eureka/
info:
  app.name: springcloudhelloworld
  company.name: www.springcloudhelloworld.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
